### ISSUE TITLE
Update to 1.6.28 , 1.6.26 has a security bug.

### ISSUE THREAD

**Issue by lexual** [conda-forge/libpng-feedstock#12]
details here: http://www.libpng.org/pub/png/libpng.html

I can take a try at updating.

**Comment by ocefpaf** [comment]
Ping @msarahan

**Comment by msarahan** [comment]
Wow, a 21-year old bug.  That's amazing!

Thanks for fixing this @lexual.

I think defaults is fine - Ilan updated to 1.6.27.  If there are compatibility issues that we find, I'll ask him to update again.

**Comment by ocefpaf** [comment]
And we talked about old, stable, and reliable libraries like `libpng` in you previous meeting :stuck_out_tongue_winking_eye:
