### ISSUE TITLE
libpng 1.6.40?

### ISSUE THREAD

**Issue by dholzber** [conda-forge/libpng-feedstock#40]
### Comment:

Any ETA on when 1.6.40 will be uploaded?

**Comment by ocefpaf** [comment]
> Any ETA on when 1.6.40 will be uploaded?

There is a PR in #39. If you can help fix that one we can merge it.

**Comment by pkgw** [comment]
We are now up to 1.6.42 in #42. I'm hopeful that it will now be building correctly with a couple of tweaks that I just put in.

**Comment by ocefpaf** [comment]
Closing this. Let me know if the latest version works for you.
